### ISSUE TITLE
PhotoMetadata from Container 

### ISSUE THREAD

**Issue by urmichm** [urmichm/places-placesearch-ktx#5]
**PhotoMetadataContainer to convert into PhotoMetadata**

```
 PhotoMetadata.builder(this.photoReference)
             .setAttributions(this.attributions[0])
```

**Triggers exception:**
```
Exception in thread "CoroutineScheduler-worker-2" java.lang.RuntimeException: Stub!
 at android.text.TextUtils.isEmpty(TextUtils.java:59)
 at com.google.android.libraries.places.api.model.PhotoMetadata$Builder.build(com.google.android.libraries.places:places@@2.5.0:4)
 at com.github.urmichm.diana.containers.PhotoMetadataContainer.toPhotoMetadata(PhotoMetadataContainer.kt:22)
```

**Comment by urmichm** [comment]
TBD in the next release
